trigger:
  tags:
    include:
      - v*
      - init*

pr: none

pool:
  name: Default

variables:
  - group: GitHubSecrets
  - name: TAG_NAME
    value: $[replace(variables['Build.SourceBranch'], 'refs/tags/', '')]

steps:
- checkout: self
  fetchDepth: 0


- script: |
    set -e
    
    git config user.email "noreply@example.com"
    git config user.name "Pipeline"
    
    # git-filter-repo ã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ï¼ˆpip ã®ãƒ‘ã‚¹ã‚’æ˜Žç¤ºï¼‰
    pip install git-filter-repo --break-system-packages || pip install git-filter-repo
    export PATH="$HOME/.local/bin:$PATH"
    
    # GitHub ãƒªãƒ¢ãƒ¼ãƒˆã‚’è¨­å®šï¼ˆæ—¢å­˜ãªã‚‰å‰Šé™¤ã—ã¦å†è¿½åŠ ï¼‰
    git remote remove github 2>/dev/null || true
    git remote add github https://$(GITHUB_PAT)@github.com/seven-eight-nine/tomato.git
    
    # init ã‚¿ã‚°ã‹ã©ã†ã‹ã‚’åˆ¤å®š
    IS_INIT=false
    if [[ "$(TAG_NAME)" == init* ]]; then
      IS_INIT=true
      echo "ðŸ”¥ Init tag detected: $(TAG_NAME)"
      echo "   GitHub repository will be completely reset!"
    fi
    
    # ã‚¿ã‚°ãŒæ—¢ã«å­˜åœ¨ã™ã‚‹ã‹ãƒã‚§ãƒƒã‚¯ï¼ˆinitä»¥å¤–ã®å ´åˆï¼‰
    if [ "$IS_INIT" = false ]; then
      if git ls-remote --tags github | grep -q "refs/tags/$(TAG_NAME)$"; then
        echo "Tag $(TAG_NAME) already exists on GitHub, skipping"
        exit 0
      fi
    fi
    
    # æ—¢å­˜ã®ãƒ–ãƒ©ãƒ³ãƒã‚’å‰Šé™¤
    git branch -D github-main 2>/dev/null || true
    
    # GitHub ã® main ã‚’å–å¾—ï¼ˆinitã®å ´åˆã¯ã‚¹ã‚­ãƒƒãƒ—ï¼‰
    if [ "$IS_INIT" = false ]; then
      git fetch github main:github-main 2>/dev/null || echo "No existing main on GitHub"
    fi
    
    # ä½œæ¥­ç”¨ãƒ–ãƒ©ãƒ³ãƒä½œæˆ
    if [ "$IS_INIT" = true ]; then
      # init: å®Œå…¨ã«æ–°è¦ä½œæˆï¼ˆGitHubå´ã®å±¥æ­´ã‚’ç ´æ£„ï¼‰
      echo "Creating fresh orphan branch..."
      git checkout --orphan github-main
      git reset --hard
      git checkout $(Build.SourceVersion) -- .
      
    elif git rev-parse github-main >/dev/null 2>&1; then
      # GitHub ã« main ãŒå­˜åœ¨ã™ã‚‹å ´åˆ
      git checkout github-main
      
      # å…¨ãƒ•ã‚¡ã‚¤ãƒ«å‰Šé™¤
      find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
      
      # Azure DevOps ã®ãƒ•ã‚¡ã‚¤ãƒ«ã‚’ã‚³ãƒ”ãƒ¼
      git checkout $(Build.SourceVersion) -- .
    else
      # GitHub ã« main ãŒãªã„å ´åˆï¼ˆåˆå›žï¼‰
      git checkout --orphan github-main
      git reset --hard
      git checkout $(Build.SourceVersion) -- .
    fi
    
    # Azure Pipeline é–¢é€£ãƒ•ã‚¡ã‚¤ãƒ«ã‚’ç¢ºå®Ÿã«é™¤å¤–
    rm -rf .azure-pipelines azure-pipelines.yml
    git rm -rf --cached .azure-pipelines azure-pipelines.yml 2>/dev/null || true
    
    echo "=== Files to be committed ==="
    ls -la
    echo "=== Checking .azure-pipelines ==="
    ls -la .azure-pipelines 2>/dev/null && echo "WARNING: .azure-pipelines still exists!" || echo "OK: .azure-pipelines removed"
    echo "=== End of file list ==="
    
    # ã‚³ãƒŸãƒƒãƒˆ
    git add -A
    git commit -m "Release $(TAG_NAME)" || echo "No changes to commit"
    
    # æœ€æ–°ã‚³ãƒŸãƒƒãƒˆã®ãƒãƒƒã‚·ãƒ¥ã‚’å–å¾—
    LATEST_COMMIT=$(git rev-parse HEAD)
    RELEASE_DATE=$(date +%s)
    
    # ã‚³ãƒŸãƒƒã‚¿ãƒ¼æƒ…å ±ã‚’åŒ¿ååŒ–
    # - Authorå/ãƒ¡ãƒ¼ãƒ«: å…¨ã‚³ãƒŸãƒƒãƒˆå¯¾è±¡
    # - æ™‚åˆ»: æœ€æ–°ã‚³ãƒŸãƒƒãƒˆã®ã¿å¤‰æ›´
    echo "if commit.original_id == b'${LATEST_COMMIT}':" > /tmp/callback.py
    echo "    commit.author_date = b'${RELEASE_DATE} +0000'" >> /tmp/callback.py
    echo "    commit.committer_date = b'${RELEASE_DATE} +0000'" >> /tmp/callback.py
    
    git filter-repo --force \
      --email-callback 'return b"noreply@example.com"' \
      --name-callback 'return b"Pipeline"' \
      --commit-callback "$(cat /tmp/callback.py)"
    
    # ãƒªãƒ¢ãƒ¼ãƒˆã‚’å†è¿½åŠ ï¼ˆfilter-repo ã§æ¶ˆãˆã‚‹ãŸã‚ï¼‰
    git remote remove github 2>/dev/null || true
    git remote add github https://$(GITHUB_PAT)@github.com/seven-eight-nine/tomato.git
    
    # æ—¢å­˜ã®ã‚¿ã‚°ã‚’å‰Šé™¤ã—ã¦å†ä½œæˆ
    git tag -d $(TAG_NAME) 2>/dev/null || true
    git tag -a $(TAG_NAME) -m "Release $(TAG_NAME)"
    
    # ãƒ—ãƒƒã‚·ãƒ¥ï¼ˆå±¥æ­´æ›¸ãæ›ãˆã®ãŸã‚ forceï¼‰
    git push github github-main:main --force
    git push github $(TAG_NAME) --force
    
    # init ã®å ´åˆã€å¤ã„ã‚¿ã‚°ã‚’å‰Šé™¤
    if [ "$IS_INIT" = true ]; then
      echo "Cleaning up old tags on GitHub..."
      git ls-remote --tags github | awk '{print $2}' | sed 's/\^{}$//' | sort -u | grep -v "^refs/tags/$(TAG_NAME)$" | while read tag; do
        tag_name=${tag#refs/tags/}
        echo "Deleting tag: $tag_name"
        git push github --delete "refs/tags/$tag_name" 2>/dev/null || true
      done
    fi
    
    echo "âœ… Successfully pushed to GitHub"
  displayName: Push to GitHub with tag